# Generated by Django 2.1.7 on 2021-04-20 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookmarked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbyuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userprofile.User_profileing')),
            ],
        ),
        migrations.CreateModel(
            name='draftblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtitle', models.CharField(max_length=500)),
                ('dcontent', models.CharField(max_length=3000)),
                ('dimage', models.CharField(max_length=200)),
                ('dbyuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userprofile.User_profileing')),
            ],
        ),
        migrations.CreateModel(
            name='publishedblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=3000)),
                ('image', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('byuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userprofile.User_profileing')),
            ],
        ),
        migrations.AddField(
            model_name='bookmarked',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.publishedblog'),
        ),
    ]
