# Generated by Django 2.1.7 on 2021-05-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_bookmarked_bbyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftblog',
            name='summary',
            field=models.CharField(default=11, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publishedblog',
            name='summary',
            field=models.CharField(default=11, max_length=3000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='draftblog',
            name='dcontent',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='draftblog',
            name='dimage',
            field=models.ImageField(upload_to='media/dblog'),
        ),
        migrations.AlterField(
            model_name='publishedblog',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publishedblog',
            name='image',
            field=models.ImageField(upload_to='media/pblog'),
        ),
    ]
