# Generated by Django 2.1.7 on 2021-05-09 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210505_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draftblog',
            old_name='summary',
            new_name='dsummary',
        ),
    ]
