# Generated by Django 2.1.7 on 2021-05-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210509_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draftblog',
            old_name='dimage',
            new_name='dimage1',
        ),
        migrations.RenameField(
            model_name='publishedblog',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='draftblog',
            name='dimage2',
            field=models.ImageField(default=1, upload_to='media/dblog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='draftblog',
            name='dimage3',
            field=models.ImageField(default=1, upload_to='media/dblog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publishedblog',
            name='image2',
            field=models.ImageField(default=1, upload_to='media/pblog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publishedblog',
            name='image3',
            field=models.ImageField(default=1, upload_to='media/pblog'),
            preserve_default=False,
        ),
    ]
