# Generated by Django 2.1.7 on 2021-05-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210510_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftblog',
            name='dtags',
            field=models.CharField(default=1, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publishedblog',
            name='tags',
            field=models.CharField(default=1, max_length=3000),
            preserve_default=False,
        ),
    ]
