# Generated by Django 2.1.7 on 2021-04-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profileing',
            name='image',
            field=models.ImageField(default=0, upload_to='user_faces/'),
            preserve_default=False,
        ),
    ]
