# Generated by Django 2.1.7 on 2021-04-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_user_profileing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profileing',
            name='image',
            field=models.TextField(),
        ),
    ]
