# Generated by Django 2.1.7 on 2021-05-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20210424_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profileing',
            name='image64',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
