# Generated by Django 2.1.7 on 2021-05-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_user_profileing_image64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profileing',
            name='c_password',
        ),
    ]
